function createfigure(X1, YMatrix1, Parent1)
%CREATEFIGURE(X1, YMatrix1, Parent1)
%  X1:  vector of stairs x data
%  YMATRIX1:  matrix of stairs y data
%  PARENT1:  text parent

%  Auto-generated by MATLAB on 16-Nov-2023 15:47:40

% Create figure
figure('Tag','ScopePrintToFigure',...
    'Color',[0.156862745098039 0.156862745098039 0.156862745098039],...
    'OuterPosition',[935 240 590 489]);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
axes1 = axes('Tag','DisplayAxes1_RealMag');
hold(axes1,'on');
colororder([1 1 0.0666666666666667;0.0745098039215686 0.623529411764706 1;1 0.411764705882353 0.16078431372549;0.392156862745098 0.831372549019608 0.0745098039215686;0.717647058823529 0.274509803921569 1;0.0588235294117647 1 1;1 0.0745098039215686 0.650980392156863]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create multiple stair objects using matrix input to stairs
stairs1 = stairs(X1,YMatrix1,'LineWidth',0.75,'Parent',axes1);
set(stairs1(1),'DisplayName','Sum:1','Tag','DisplayLine1',...
    'Color',[1 1 0.0666666666666667]);
set(stairs1(2),'DisplayName','Sum:2','Tag','DisplayLine2',...
    'Color',[0.0745098039215686 0.623529411764706 1]);
set(stairs1(3),'DisplayName','Sum:3','Tag','DisplayLine3',...
    'Color',[1 0.411764705882353 0.16078431372549]);
set(stairs1(4),'DisplayName','Sum:4','Tag','DisplayLine4',...
    'Color',[0.392156862745098 0.831372549019608 0.0745098039215686]);
set(stairs1(5),'DisplayName','Sum:5','Tag','DisplayLine5',...
    'Color',[0.717647058823529 0.274509803921569 1]);
set(stairs1(6),'DisplayName','Sum:6','Tag','DisplayLine6',...
    'Color',[0.0588235294117647 1 1]);

% Create xlabel
xlabel(' time ');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 15]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-2.19854 4.54615]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle','Color',[0 0 0],'FontSize',8,...
    'GridAlpha',0.4,'GridColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],...
    'TickLabelInterpreter','none','XColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],'XGrid','on',...
    'YColor',[0.686274509803922 0.686274509803922 0.686274509803922],'YGrid',...
    'on','ZColor',[0.686274509803922 0.686274509803922 0.686274509803922]);
% Create text
text('Tag','TimeOffsetStatus','Parent',Parent1,'Units','pixels',...
    'VerticalAlignment','bottom',...
    'FontSize',8,...
    'Position',[0 0 0],...
    'Color',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'Visible','on');

